// import "./components/FetchAppHomePage.js"
import "./components/FetchAppSearch.js"
// import "./components/FetchAppCategoryPage.js"
import "./components/RevealSections.js"
import "./components/Header.js"
import "./components/HeroSlider.js"
